changelog:
  categories:
    - title: Breaking Changes ⚠️
      labels:
        - breaking-change
        - break
    - title: New Features 🚀
      labels:
        - feature
        - enhancement
        - feat
    - title: Bug Fixes 🐛
      labels:
        - bug
        - fix
    - title: Documentation 📖
      labels:
        - docs
    - title: Other Changes 🧑‍💻
      labels:
        - '*'
